version: '3.12'

services:
    database:
        image: idb
        container_name: db
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql